### PR TITLE
Add New-BulkZoneDeleteRequest, Get-BulkZoneDeleteStatus, and Get-BulkZoneDeleteResult

### PR DESCRIPTION
**Pull request by rmbolger**
This change adds the following functions that correlate to the Edge DNS API endpoints associated with bulk zone delete requests. The alias was added because a non-bulk delete zone endpoint doesn't currently exist within the Edge DNS API.

- `New-BulkZoneDeleteRequest` (with alias `Remove-Zone`)
- `Get-BulkZoneDeleteStatus`
- `Get-BulkZoneDeleteResult`

`New-BulkZoneDeleteRequest` takes one or more zone strings in an array directly or via the pipeline in addition to an optional `BypassSafetyChecks` switch which corresponds to the query parameter of the same name. It will also accept a raw `Body` parameter instead of the zone list. Because it's a destructive operation, I set the function's `ConfirmImpact` to `High` which will cause a confirmation prompt in a default environment unless `-Confirm:$false` is used. It also supports the native `-WhatIf` parameter.

`Get-BulkZoneDeleteStatus` and `Get-BulkZoneDeleteResult` both take a `RequestID` parameter which you get from the the `requestId` field in the returned object from `New-BulkZoneDeleteRequest`.

All three functions also include embedded comment-based help for use with `Get-Help`.

### CODE REVIEW

**Comment by stuartio** [comment]
Code looks fine, wondering about maybe a simpler name for the cmdlet though, e.g. Remove-Zone. I realise it is not a synchronous process, but might be easier. Again, happy to discuss

**Comment by rmbolger** [comment]
Yeah, I was sort of flip flopping around the naming myself. This way feels less intuitive/discoverable, but more proper(?) in describing what it's actually doing. I was hoping to eventually add the bulk create equivalents as well and there's already a singular/synchronous `New-Zone` function. So naming this `Remove-Zone` might cause it's own confusion because it doesn't really correspond to the `New-Zone` equivalent. It's weird that there's no singular/synchronous zone delete endpoint though, right?

**Comment by stuartio** [comment]
Ah I see. Yeah that is weird. So for previous cmdlets I have overloaded api endpoints with multiple requests to make it easier to figure out, e.g. when the same endpoint is used to create and update something I have created two cmdlets, just so the wacky nature of the API design is hidden from the user. So we could combine both names as a future-proofing alias I suppose, that way we can break out the logic later but the cmdlet is still discoverable? If so I would propose Remove-Zone and New-BulkDeleteRequest.

**Comment by rmbolger** [comment]
I'd probably keep the word "Zone" in there and go with `New-BulkZoneDeleteRequest` just to avoid potential conflict with other types of bulk deletes in non-EdgeDNS APIs. Were you thinking that would be the actual name and `Remove-Zone` would be the alias or vice-versa?

**Comment by stuartio** [comment]
Either option works for me. Feel free to code it either way, or even just create 2 cmdlets.

**Comment by rmbolger** [comment]
Ok, updates done.

**Comment by stuartio** [comment]
Sorry, looks like the cmdlet is still Submit-NewBulkZoneDeleteRequest rather than New-NewBulkZoneDeleteRequest . Is that deliberate?

**Comment by rmbolger** [comment]
It's currently `Submit-BulkZoneDeleteRequest` (no extra New)...but yeah, I misunderstood your naming pref. I'll update it to `New-BulkZoneDeleteRequest`.

**Pull request merged**
